# task
model = 'shufflenet'
dataset = 'cifar10'
split = 'iid'
dir_alpha = nan

# system
n_client = 20
m_client = 5
n_server = 5
m_server = 1
n_round = 250

# training
n_epoch = 3
learning_rate = 1e-3
device = 'cuda:1'
datapath = '/data'
batch_size = 32
num_workers = 2

# security
attack = 'min-max-uv'
aggregation = 'fedavg'
selection_fraction = 0.33
method = 'stateful'